### ISSUE TITLE
為什麼用手機前鏡頭直播，電腦播放器看直播的影像是180度倒過來的?

### ISSUE THREAD

**Issue by Squall-Huang** [luohaohaha/RTMPX#5]
為什麼用手機直向Portrait前鏡頭直播，電腦播放器看直播的影像是180度倒過來的?
( 但是後鏡頭是正常的)
如果手機橫向(landscape)直播，前後鏡頭在播放器看也是正常的

**Comment by luohaohaha** [comment]
> 為什麼用手機直向Portrait前鏡頭直播，電腦播放器看直播的影像是180度倒過來的? ( 但是後鏡頭是正常的) 如果手機橫向(landscape)直播，前後鏡頭在播放器看也是正常的

谢谢你的反馈，忘了前置摄像头的角度问题，我已经更新了image yuv旋转部分，暂未测试，如果你有空的话可以测试一下

**Comment by Squall-Huang** [comment]
您好:
  我沒看到您library有更新，請問您更新在哪裡??

**Comment by Squall-Huang** [comment]
您好:
  有看到更新，但是可能版號還在1.0.2，我重新拉gradle.build好像沒有用

**Comment by Squall-Huang** [comment]
您好:
我有按sync project with gradle按鈕，但情況還是沒變

**Comment by luohaohaha** [comment]
已经更新1.0.3，我测试ok

**Comment by Squall-Huang** [comment]
您好:
  播放器影像在1.0.3版有變正向了，謝謝^^

另外，請問這個lib有把相機鏡頭影像拉遠拉近的功能嗎?
有沒有比較詳細的Doc可以看呢?

**Comment by luohaohaha** [comment]
暂时还没空整理DOC，你可以看看ICamera的函数定义，大多数场景都是支持的。变焦、曝光、对焦等等...
