### ISSUE TITLE
Publish(ed) App?

### ISSUE THREAD

**Issue by colemickens** [luohaohaha/RTMPX#9]
It seems like this could provide a simple, effective, open source alternative to DroidCam.

Have y'all considered making a slightly more advanced Android app with options for the user to specify the publish URL, rather than how it's hard-coded now?

Or is there an app that is built with this? It seems too good! :) 

thank you!

**Comment by luohaohaha** [comment]
> It seems like this could provide a simple, effective, open source alternative to DroidCam.
> 
> Have y'all considered making a slightly more advanced Android app with options for the user to specify the publish URL, rather than how it's hard-coded now?
> 
> Or is there an app that is built with this? It seems too good! :)
> 
> thank you!

Of course, it seems that I have to rewrite my sample

**Comment by colemickens** [comment]
Sorry to be so needy, is there any chance you'd upload the APK as part of the build? I think the AAR that is part of the release now is just the library?
